[package]
name = "venn-diagrams"
version = "0.1.0"
edition = "2024"

[dependencies]
itertools = "0.14.0"
svg = "0.18.0"

[lints.clippy]
needless_range_loop = "allow"

[dev-dependencies]
insta = "1.43.2"
